# Generated by Django 4.2.4 on 2024-04-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_remove_appointment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='image',
            field=models.ImageField(blank=True, default='https://www.universodelasaludanimal.com/wp-content/uploads/sites/61/2021/07/Cacho-e-gato-juntos-no-chao-posando-pra-foto_3.jpg', null=True, upload_to='images/'),
        ),
    ]
