# Generated by Django 4.2.4 on 2024-05-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_producto_cantidad_pagopaypal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagoPaypal',
        ),
    ]
